### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by bfontaine** [joshb/DromeAudio#2]
Hello,
It would be great to have _tagged_ releases, so we could use them to include DromeAudio in the [Homebrew](http://brew.sh/) core.
Thanks!

**Comment by joshb** [comment]
Thanks for the suggestion - created a tagged release here: https://github.com/joshb/DromeAudio/releases/tag/v0.3.0

**Comment by bfontaine** [comment]
Thanks a lot :smile:
